version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      PORT: 3000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: products_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata: